--[[
* **********************************************************************
 * ISEMS LUA source code for OSPIT
 * Copyright (C) 2026  by Corinna 'Elektra' Aichele with contributions
 * by Andreas Motl
 *
 * This file is part of the Open-Hardware and Open-Software project 
 * FF-ESP32-OpenMPPT.
 * 
 * This file is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This source code is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this source file. If not, see http://www.gnu.org/licenses/. 
 ************************************************************************* ]]


-- Print with verbosity level 0:Critical,1:Error,2:Info,3:Debug,4:Trace
function printv(v,...)
    if (verbose == nil or verbose >= v) then
        print(...)
    end
end

function sh()
    require('shell').run()
end

battery_temperature = 25
heatsink_temperature = 25
-- Use pump port as default load port
pump_is_load=true



gpio.config( { gpio={12, 13, 14, 26, 27}, dir=gpio.OUT, pull=gpio.PULL_UP_DOWN } )
gpio.write(12, 0)
gpio.write(13, 0)
gpio.write(14, 0)
gpio.write(26, 0)
gpio.write(27, 0)

valve_1_enabled = false
valve_2_enabled = false
valve_3_enabled = false

--Modbus UART Setup

-- UART Setup for OpenMPPT UEXT Header (example using UART2)
-- SEN0600 default: 9600 baud, 8N1

uart.setup(2, 9600, 8, uart.PARITY_NONE, uart.STOPBITS_1, {tx = 17, rx = 16} )

uart.start(2)

-- Initialize one wire bus global variables for other FreeRTOS tasks to read
-- Setting to -127 indicates "Not yet read" or "Missing"
airtemp  = -127
battery_temperature = -127
pcbtemp  = -127
bme280_temperature = -127
bme280_humidity = -127
bme280_pressure = -127
bh1750_lux = -127

dofile"owread.lua"

dofile"modbr.lua"

if bme280_enabled or bh1750_enabled then
    env_sensors = dofile"env_sensors.lua"
    env_sensors:read()
end

if nodeid == "ESP32-Meshnode-Unconfigured" then nodeid = "FF-ESP-Unconfigured-" .. node.chipid() 
printv(1,"Unique Node-ID not set. Please fix this.\nUsing autogenerated Node-ID: ", nodeid)
end



adc.setwidth(adc.ADC1, 12)

adc.setup(adc.ADC1, 6, adc.ATTEN_0db)
adc.setup(adc.ADC1, 5, adc.ATTEN_0db)
adc.setup(adc.ADC1, 4, adc.ATTEN_11db)

gpio.config( { gpio={14}, dir=gpio.OUT, pull=gpio.PULL_UP })
dac.enable(dac.CHANNEL_1)

dac1value = 0

Voutctrlcounter = 0
health_estimate = 100
health_test_in_progress = false
V_oc = 0


load_disabled = false

-- Calibration data
-- MPP range of FF-OpenMPPT-ESP32 v1.2
if not Vmpp_max then Vmpp_max = 27.2 end
if not Vmpp_min then Vmpp_min = 13.25 end
if not Vcc then Vcc = 3.07 end
if not hardware_version then hardware_version = "unknown" end
if not firmware_type then firmware_type = "unknown" end

-- pagestring = "mp2.lua not started yet."

V_outctrltimer = tmr.create()
V_outctrltimer:register(600, tmr.ALARM_AUTO, function() Voutctrl(1) end)

autoreboot_disabled = 0
require"mp2"
if nextreboot == nil then nextreboot = 99999 end
if nextreboot == 0 then autoreboot_disabled = 1 end

print("Autoreboot_disabled  =", autoreboot_disabled)



packetrev = "1"
counter_serial_loop = 0
health_estimate = 100
powersave = 0
timestamp = 123456789
health_estimate = 100
charge_state = 100

--if (ow18b20 == true) then
    ow18b20timer = tmr.create()
    ow18b20timer:register(12000, tmr.ALARM_AUTO, function() dofile"owread.lua" end)
    ow18b20timer:start()
--end


mppttimer = tmr.create()
mppttimer:register(15000, tmr.ALARM_AUTO, function() dofile"mp2.lua" if autoreboot_disabled ~= 1 then nextreboot = nextreboot - 1 end
if autoreboot ~= 1 and nextreboot <= -1 then node.restart() end end)
mppttimer:start()

if mqtt_enabled then
mqtttimer = tmr.create()
mqtttimer:register(65000, tmr.ALARM_AUTO, function() 
                   printv(2,"MQTT telemetry process started")
		   if Voutctrlcounter > 0  then V_outctrltimer:stop() end 
                   dofile"telemetry.lua" 
                   if Voutctrlcounter > 0  then V_outctrltimer:start() end
                  end)
mqtttimer:start()
end

if bme280_enabled or bh1750_enabled then
    env_sensor_timer = tmr.create()
    env_sensor_timer:register(env_sensor_interval_ms or 30000, tmr.ALARM_AUTO, function()
        env_sensors:read()
    end)
    env_sensor_timer:start()
end

if i_nbld == true then 
    irr_watchdog = tmr.create()
    irr_watchdog:register(6000, tmr.ALARM_AUTO, function() 
    dofile"irrigation.lua"
    end)
    irr_watchdog:start()
end


tankgauge = -1
humidity1 = -1
humidity2 = -1
humidity3 = -1 
